---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.16
  commands:
  - go test ./... -cover -v

- name: lint
  image: golangci/golangci-lint:v1.38.0
  commands:
  - golangci-lint run

- name: build
  image: golang:1.16
  commands:
  - CGO_ENABLED=0 GOOS=linux go build -o main

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO,,}
    username:
      from_secret: docker_username

trigger:
  branch:
  - master

...
