---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.15
  commands:
  - go test -v -cover

- name: build
  image: golang:1.15
  commands:
  - CGO_ENABLED=0 GOOS=linux go build

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO,,}
    username:
      from_secret: docker_username

...
