kind: pipeline
name: default
trigger:
  branch:
    - master
steps:
  - name: test
    image: 'golang:1.12.6'
    commands:
      - 'go test'
      - 'CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags ''-extldflags "-static"'' -o main .'
      
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      cache_from: '${DRONE_REPO,,}:latest'
      repo: '${DRONE_REPO,,}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
